services:
  postgres:
    image: postgres:15
    container_name: notification_service_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: networkpro_notification_service
      POSTGRES_USER: notification_service
      POSTGRES_PASSWORD: password
    ports:
      - "5456:5432"
    volumes:
      - pgdata_notification_service:/var/lib/postgresql/data
volumes:
  pgdata_notification_service:
