services:
  postgres:
    image: postgres:15
    container_name: networkpro_connection_service_container
    environment:
      POSTGRES_DB: networkpro_connection_service
      POSTGRES_USER: connection_service
      POSTGRES_PASSWORD: password
    ports:
      - "5459:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
