services:
  postgres:
    image: postgres:15
    container_name: networkpro_post_service_container
    environment:
      POSTGRES_DB: network_post_service
      POSTGRES_USER: post_service
      POSTGRES_PASSWORD: password
    ports:
      - "5460:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
